import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/ui/NavBar";
import { Providers } from "./providers";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black ">
        <header className="text-white">
          <NavBar />
        </header>

        <Providers>

          {children}

        </Providers>

        <footer className="text-white">Footer</footer>
      </body>
    </html>
  );
}
